# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='pcap',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='updater.Pcap'),
        ),
        migrations.AddField(
            model_name='link',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
