# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='geoposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
    ]
