# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('mac', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fabricante', models.CharField(max_length=200)),
            ],
        ),
    ]
