# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dns_useragent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useragent',
            old_name='platform',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='useragent',
            old_name='version',
            new_name='os',
        ),
    ]
