# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcap',
            name='procesado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
